### ISSUE TITLE
Book really needs some code update

### ISSUE THREAD

**Issue by viniciusccarvalho** [davecom/ClassicComputerScienceProblemsInJava#8]
Found a bunch of code errors on Chapter 2, and seems that they have been fixed here, would be nice to have the book updated to reflect the code.

For instance `Node<MazeLocation> solution1 = GenericSearch.dfs(m.start, m::goalTest, m::successors);` `start` property is final.

Glad to see that the enum `switch` was also replaced by proper enum declaration ...

**Comment by davecom** [comment]
HI @viniciusccarvalho,

Thanks for reaching out. The online version of the book likely won't get an update again by the publisher for several weeks.

We made several stylistic code changes here over the past two weeks that are not yet reflected in the book.

However, I am not aware of any errors, so can you point me to all of the specific code listings that have errors? We only made stylistic changes, and as far as we are aware and have heard from other readers all of the code was running, so we really need to know about these.

Thanks,
David

**Comment by davecom** [comment]
I haven't heard any details from you, so I'm going to close this. Feel free to reopen if you'd like to provide them. Thanks.
